
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Apr 24 17:45:54 KST 2015
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int WHILE = 3;
  public static final int GE = 14;
  public static final int NUMBER = 8;
  public static final int THEN = 4;
  public static final int EQ = 11;
  public static final int EOF = 0;
  public static final int STRING = 7;
  public static final int LE = 10;
  public static final int IF = 2;
  public static final int GT = 13;
  public static final int ELSE = 5;
  public static final int error = 1;
  public static final int IDENTIFIER = 6;
  public static final int NE = 12;
  public static final int LT = 9;
}

